/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.student.attendence.studentattendencesystem.views;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author fiston
 */
public class SignUpView extends javax.swing.JFrame {
        private final String url = "jdbc:mysql://localhost/SAS";
        private final String username = "root";
        private final String password = "";

	/**
	 * Creates new form LoginView
	 */
	public SignUpView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                buttonGroup2 = new javax.swing.ButtonGroup();
                buttonGroup3 = new javax.swing.ButtonGroup();
                LoginPanel = new javax.swing.JPanel();
                logoIconLabel = new javax.swing.JLabel();
                usernameLabel = new javax.swing.JLabel();
                usernameTextField = new javax.swing.JTextField();
                passwordLabel = new javax.swing.JLabel();
                signUpButton = new javax.swing.JButton();
                ahaLabel = new javax.swing.JLabel();
                signUpLabel = new javax.swing.JLabel();
                passwordTextField = new javax.swing.JPasswordField();
                urLabel = new javax.swing.JLabel();
                fnameTextField = new javax.swing.JTextField();
                fnameLabel = new javax.swing.JLabel();
                lnameTextField = new javax.swing.JTextField();
                lnameLabel = new javax.swing.JLabel();
                emailTextField = new javax.swing.JTextField();
                emailLabel = new javax.swing.JLabel();
                staffRadioButton = new javax.swing.JRadioButton();
                roleLabel = new javax.swing.JLabel();
                studentRadioButton = new javax.swing.JRadioButton();
                adminRadioButton = new javax.swing.JRadioButton();
                accessPasswordField = new javax.swing.JPasswordField();
                accessLabel = new javax.swing.JLabel();
                confirmPasswordLabel = new javax.swing.JLabel();
                confirmPasswordTextField = new javax.swing.JPasswordField();
                backgroundIconLabel = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                LoginPanel.setBackground(new java.awt.Color(255, 255, 255));

                logoIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                logoIconLabel.setIcon(new javax.swing.ImageIcon("/home/fiston/Documents/signuplogo.png")); // NOI18N
                logoIconLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                usernameLabel.setText("Student ID:");

                usernameTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                usernameTextFieldActionPerformed(evt);
                        }
                });

                passwordLabel.setText("Password");

                signUpButton.setBackground(new java.awt.Color(48, 100, 159));
                signUpButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
                signUpButton.setForeground(new java.awt.Color(255, 255, 255));
                signUpButton.setText("Sign Up");
                signUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                signUpButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
                signUpButton.setIconTextGap(0);
                signUpButton.setName(""); // NOI18N
                signUpButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                signUpButtonActionPerformed(evt);
                        }
                });

                ahaLabel.setForeground(new java.awt.Color(51, 51, 51));
                ahaLabel.setText("Aleady have an account?");

                signUpLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
                signUpLabel.setForeground(new java.awt.Color(53, 116, 255));
                signUpLabel.setText(" Log In");
                signUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                signUpLabelMouseClicked(evt);
                        }
                });

                urLabel.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
                urLabel.setForeground(new java.awt.Color(3, 44, 106));
                urLabel.setText("User Registration");

                fnameTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fnameTextFieldActionPerformed(evt);
                        }
                });

                fnameLabel.setText("First Name:");

                lnameTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lnameTextFieldActionPerformed(evt);
                        }
                });

                lnameLabel.setText("Last Name:");

                emailTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                emailTextFieldActionPerformed(evt);
                        }
                });

                emailLabel.setText("Email:");

                staffRadioButton.setText("Staff");
                staffRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                staffRadioButtonActionPerformed(evt);
                        }
                });

                roleLabel.setText("Role");

                studentRadioButton.setText("Student");
                studentRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                studentRadioButtonActionPerformed(evt);
                        }
                });

                adminRadioButton.setText("Admin");
                adminRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                adminRadioButtonActionPerformed(evt);
                        }
                });

                accessLabel.setText("Access Code:");

            accessLabel.setText("Access Code:");
            accessLabel.setVisible(false);
            accessPasswordField.setVisible(false);
            accessPasswordField.getDocument().addDocumentListener(new DocumentListener() {
                    @Override
                    public void insertUpdate(DocumentEvent e) {
                            getAccess();
                    }

                    @Override
                    public void removeUpdate(DocumentEvent e) {
                            getAccess();
                    }

                    @Override
                    public void changedUpdate(DocumentEvent e) {
                            getAccess();
                    }
            });

                confirmPasswordLabel.setText("Confirm Password");

                javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
                LoginPanel.setLayout(LoginPanelLayout);
                LoginPanelLayout.setHorizontalGroup(
                        LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                                .addGap(0, 149, Short.MAX_VALUE)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel)
                                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                                                        .addComponent(logoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(142, 142, 142))
                                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(usernameTextField)
                                                                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                                                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                                                                                .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(51, 51, 51))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginPanelLayout.createSequentialGroup()
                                                                                                .addComponent(fnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(lnameLabel)
                                                                                        .addComponent(lnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginPanelLayout.createSequentialGroup()
                                                                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(passwordLabel)
                                                                                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(confirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(confirmPasswordLabel))))
                                                                .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                                                        .addComponent(studentRadioButton)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(staffRadioButton)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(adminRadioButton))
                                                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                                                        .addComponent(accessLabel)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(accessPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(155, 155, 155)))))
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(ahaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signUpLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                                                .addComponent(urLabel)
                                                .addGap(205, 205, 205))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(263, 263, 263))))
                );
                LoginPanelLayout.setVerticalGroup(
                        LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(logoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urLabel)
                                .addGap(18, 18, 18)
                                .addComponent(usernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fnameLabel)
                                        .addComponent(lnameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel)
                                        .addComponent(confirmPasswordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(confirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(roleLabel)
                                .addGap(15, 15, 15)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(staffRadioButton)
                                        .addComponent(adminRadioButton)
                                        .addComponent(studentRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(accessLabel)
                                        .addComponent(accessPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(signUpLabel)
                                        .addComponent(ahaLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                backgroundIconLabel.setIcon(new javax.swing.ImageIcon("/home/fiston/Documents/loginBackground.png")); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backgroundIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(backgroundIconLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_usernameTextFieldActionPerformed

        private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
               int studentId = Integer.parseInt(usernameTextField.getText());
               String firstName = fnameTextField.getText();
                String lastName = lnameTextField.getText();
                String email = emailTextField.getText();
                String password = passwordTextField.getText();
                String confirmPassword = confirmPasswordTextField.getText();
                String role;
                if (studentRadioButton.isSelected()){
                         role = "Student";
                }else if(staffRadioButton.isSelected()){
                         role = "Staff";
                } else if (adminRadioButton.isSelected()) {
                         role = "Admin";
                } else {
                         role = null;
                }

                String query = "INSERT INTO SAS.Users(UserID, FirstName, LastName, Email, Password, Role) VALUES (?, ?, ?, ?, ?, ?)";

                        try (Connection con = DriverManager.getConnection(this.url, this.username, this.password);
                             PreparedStatement insert = con.prepareStatement(query)) {

                                insert.setInt(1, studentId);
                                insert.setString(2, firstName);
                                insert.setString(3, lastName);
                                insert.setString(4, email);
                                insert.setString(5, password);
                                insert.setString(6, role);


                                int rowsAffected = insert.executeUpdate();

                                if (rowsAffected > 0) {
                                        usernameTextField.setText(null);
                                        fnameTextField.setText(null);
                                        lnameTextField.setText(null);
                                        emailTextField.setText(null);
                                        passwordTextField.setText(null);
                                        confirmPasswordTextField.setText(null);
                                        adminRadioButton.setSelected(false);
                                        staffRadioButton.setSelected(false);
                                        studentRadioButton.setSelected(false);
                                        accessLabel.setVisible(false);
                                        accessPasswordField.setVisible(false);
                                        showMessageDialog(this, "User Registered Successfully!!");
                                        LoginView login = new LoginView();
                                        login.setVisible(true);
                                        dispose();
                                } else {
                                        showMessageDialog(this, "User not Registered due to unexpected error.");
                                }

                        } catch (SQLException e) {
                                Logger.getLogger(SignUpView.class.getName()).log(Level.SEVERE, null, e);
                                showMessageDialog(this, "Database Error: " + e.getMessage());
                        }
    }

        private void signUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseClicked
            LoginView login = new LoginView();
            login.setVisible(true);
            dispose();
        }

        private void fnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_fnameTextFieldActionPerformed

        private void lnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTextFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_lnameTextFieldActionPerformed

        private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_emailTextFieldActionPerformed

        private void adminRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioButtonActionPerformed
                boolean isSelected = adminRadioButton.isSelected();
                accessLabel.setVisible(isSelected);
                accessPasswordField.setVisible(isSelected);
                staffRadioButton.setSelected(false);
                studentRadioButton.setSelected(false);
                adminRadioButton.setSelected(false);

        }

        private void staffRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffRadioButtonActionPerformed
                boolean isSelected = staffRadioButton.isSelected();
                accessLabel.setVisible(isSelected);
                accessPasswordField.setVisible(isSelected);
                adminRadioButton.setSelected(false);
                studentRadioButton.setSelected(false);
                staffRadioButton.setSelected(false);

        }

        private void studentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadioButtonActionPerformed

                adminRadioButton.setSelected(false);
                staffRadioButton.setSelected(false);
                accessLabel.setVisible(false);
                accessPasswordField.setVisible(false);
        }

        private void getAccess(){
                int pass = Integer.parseInt(accessPasswordField.getText());
                int digits = pass == 0 ? 1 : (int) Math.log10(Math.abs(pass)) + 1;

                if (pass == 4444 && digits == 4){
                        staffRadioButton.setSelected(false);
                        adminRadioButton.setSelected(true);
                        studentRadioButton.setSelected(false);
                }else if(pass == 3333 && digits == 4) {
                        adminRadioButton.setSelected(false);
                        staffRadioButton.setSelected(true);
                        studentRadioButton.setSelected(false);
                }else {
                        adminRadioButton.setSelected(false);
                        staffRadioButton.setSelected(false);
                        studentRadioButton.setSelected(false);
                }
        }

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SignUpView().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel LoginPanel;
        private javax.swing.JLabel accessLabel;
        private javax.swing.JPasswordField accessPasswordField;
        private javax.swing.JRadioButton adminRadioButton;
        private javax.swing.JLabel ahaLabel;
        private javax.swing.JLabel backgroundIconLabel;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.ButtonGroup buttonGroup2;
        private javax.swing.ButtonGroup buttonGroup3;
        private javax.swing.JLabel confirmPasswordLabel;
        private javax.swing.JPasswordField confirmPasswordTextField;
        private javax.swing.JLabel emailLabel;
        private javax.swing.JTextField emailTextField;
        private javax.swing.JLabel fnameLabel;
        private javax.swing.JTextField fnameTextField;
        private javax.swing.JLabel lnameLabel;
        private javax.swing.JTextField lnameTextField;
        private javax.swing.JLabel logoIconLabel;
        private javax.swing.JLabel passwordLabel;
        private javax.swing.JPasswordField passwordTextField;
        private javax.swing.JLabel roleLabel;
        private javax.swing.JButton signUpButton;
        private javax.swing.JLabel signUpLabel;
        private javax.swing.JRadioButton staffRadioButton;
        private javax.swing.JRadioButton studentRadioButton;
        private javax.swing.JLabel urLabel;
        private javax.swing.JLabel usernameLabel;
        private javax.swing.JTextField usernameTextField;
}
